# Generated by Django 5.2.6 on 2025-10-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('footwear', 'Footwear'), ('apparel', 'Apparel'), ('accessories', 'Accessories')], max_length=100),
        ),
    ]
